server:
  port: 8080
  
spring:
  application:
    name: ead.api-gateway
    #definindo as rotas
  cloud:
    gateway:
      routes:
      - id: user-service
        #uri: http://localhost:8087 sem o uso dinamico do eureka(esse url esta fixa)
        uri: lb://EAD-USER-SERVICE # end do eureka
        predicates:
        - Path=/ead-user/**
      - id: course-service
        #uri: http://localhost:8082 sem o uso dinamico do eureka(esse url esta fixa)
        uri: lb://EAD-COURSE-SERVICE # end do eureka
        predicates:
        - Path=/ead-course/**
        
        
#config do eureka       
eureka:
  client:
    service-url: 
       defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost         